#!/bin/bash
echo "******************************************************************"
echo "Install_Chrome "
echo "Starting Installation...."
echo "******************************************************************"
sudo ls /root
sleep 1
sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' 
sudo apt-get update 
sudo apt-get install google-chrome-stable 
google-chrome
echo "******************************************************************"
echo "Install_Chrome V.230910"
echo "Completed, Thanks NR !!!"
echo "******************************************************************"

