#!/bin/bash
clear
echo "******************************************************************"
echo "Like Linux Update_Scrip_180624"
echo "Starting Update...."
date
echo "Kernel: " 
uname -r
echo "******************************************************************"
sudo ls /root
sleep 1
sudo apt-get autoremove 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get autoremove
sudo apt-get clean
echo "******************************************************************"
./mandarmail.sh "Update Ubuntu " "nrosas@zebra.com" "Update"
echo "Correo enviado"
echo "******************************************************************"
echo "Update_Scrip_180624"
date
echo "Completed, Thanks NR !!!"
echo "******************************************************************"
exit
